### ISSUE TITLE
Wrong button depressed when multiple buttons present

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-core#576] opened 2015-08-20 18:26 UTC
Check out this project: https://beta.webmaker.org/#/project?user=462792&project=9825

Pretty hard to reproduce consistently (I'm using desktop Chrome).

There are two pages, each with a button linked to the other page. If you click on the buttons so that the projects moves back and forth, eventually, the wrong button will depress on mouse down. Sometimes, clicking on images before buttons will make this happen.

**Comment by xmatthewx** [comment] 2015-08-21 14:05
I couldn't reproduce this.

**Comment by secretrobotron** [comment] 2015-08-21 15:59
Keep trying in browser. It happened to me quite a bit yesterday while I was flipping through projects. Hard to reproduce all the time though.

**Comment by xmatthewx** [comment] 2015-08-31 20:58
I'd wager this is related to #586

**Comment by k88hudson** [comment] 2015-09-16 15:16
Resolved by gavin's #586 patch

**Closed as completed by k88hudson** 2015-09-16 15:16 UTC
Labels: bug
