### ISSUE TITLE
When Setting a Destination for the Button Element, I'm not shown what page I'm currently on.

### ISSUE THREAD

**Issue by flukeout** [mozilla/webmaker-core#522] opened 2015-08-12 22:25 UTC
This is the view I see when setting the button destination right now...

![image](https://cloud.githubusercontent.com/assets/25212/9279761/8ae64d90-426e-11e5-925d-239684d765df.png)

It's supposed to indicate which page the button is on currently, but doesn't.
These are the only two pages in my project.

**Comment by xmatthewx** [comment] 2015-08-13 17:44
This is a regression. @gvn - can you take a look? Let's assess whether or not this is a quick fix. 

Also, did we previously prevent selecting the current page as the destination (#524)?

**Comment by gvn** [comment] 2015-08-13 20:33
@Pomax I think this regression came out of the bulk work. I'm trying to debug, but so far I think it looks like a case of some data not being transferred into the Project view when setting a destination.

This general area may have something to do with it: https://github.com/mozilla/webmaker-core/blob/develop/src/pages/project/project.jsx#L60

If you could take a look as well, I'd much appreciate it!

**Comment by Pomax** [comment] 2015-08-14 17:26
Trying this with another project, I see the marker but it's on the wrong page entirely, letting me flag the page the button is _actually_ on as a destination, so yeah something is getting cached rather oddly here. Investigating

**Comment by flukeout** [comment] 2015-08-14 17:30
@Pomax I noticed that after setting it once, the 'you are here marker' appears. This is when the button destination is first set.

**Comment by Pomax** [comment] 2015-08-14 19:50
This bug is a rabbit hole. I'm finding all kinds of things related to source/destination highlighting due to how we don't create/destroy views, but create and then perpetually update them, instead

**Closed as completed** 2015-08-14 21:56 UTC
Labels: bug, in progress, Quality test
