### ISSUE TITLE
Pictures only show up on some projects

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#472] opened 2015-08-06 19:07 UTC
Some projects on the discover page, have pictures. Yet very few actually display these pictures on the thumbnail, this needs to be fixed.

**Comment by Pomax** [comment] 2015-08-11 23:23
on production, or on staging?

**Comment by ryanwarsaw** [comment] 2015-08-12 00:23
Whatever the default is, I haven't touched any of the values. Its a build I compiled from Android Studio.

**Comment by Pomax** [comment] 2015-08-12 04:47
I think for staging we're not as strict about thumbnails in the discover tab (since it's just a testing ground to make sure things work). If the real app from the play store, however, also has lots of "no thumbnails", that's a problem.

**Comment by Pomax** [comment] 2015-08-12 16:58
@xmatthewx @cadecairos I am seeing virtually no thumnails in the discovery tab on the officially available app via the play store, too.

**Comment by cadecairos** [comment] 2015-08-12 17:00
I can see all the discovery thumbnails on my device

**Comment by Pomax** [comment] 2015-08-12 17:03
I suspect this is the `<ImageLoader>` nonsense element then. Sleeping and waking up the phone again now shows all the images. We probably need to switch that thing over @gvn @k88hudson

**Comment by cadecairos** [comment] 2015-08-12 17:04
I suspected it was that bug as well.

https://api.webmaker.org/discover

none of the thumbnail urls in the json there fail to load directly

**Comment by k88hudson** [comment] 2015-08-12 18:16
@Pomax @cadecairos I've removed the image loader component, although I don't think it's on master yet

**Comment by thisandagain** [comment] 2015-08-13 18:48
Did lots of testing on this front today. Confirmed in 1.1.0 but resolved via @k88hudson 's removal of the ImageLoader component. Will ship in nightly and limited release of 1.2.0 this evening for final testing against the production / release API. Closing.

**Closed as completed by thisandagain** 2015-08-13 18:48 UTC
Labels: bug, critical, Quality test
