### ISSUE TITLE
Figure out tapping and double-tapping actions.

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#240] opened 2015-07-14 19:55 UTC
This issue has been migrated from mozilla/webmaker-android#2332.

It was originally written by [flukeout](https://api.github.com/users/flukeout) on Fri Jun 26 2015 and had the following description:

> A lot of people are double tapping elements to edit them, let's investigate this and add if appropriate. What other elements get double tapped?

**Comment by alanmoo** [comment] 2015-10-07 21:24
Duplicate of #639. @xmatthewx Should we leave that one open as the title is more descriptive/action oriented?

**Comment by xmatthewx** [comment] 2015-10-07 22:04
Sure. Closing. Tracking in #639.

**Closed as completed by xmatthewx** 2015-10-07 22:04 UTC
