### ISSUE TITLE
Sometimes ghost projects appear

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/webmaker-core#470] opened 2015-08-06 19:02 UTC
When you delete projects, sometimes it still appears even though its deleted and you can tap on the card, to get a message saying "project not found". Refreshing your page fixes the problem, the page should auto refresh once a project is deleted instead.

**Comment by Pomax** [comment] 2015-08-11 23:24
closing as duplicate of #457

**Closed as completed by Pomax** 2015-08-11 23:24 UTC
