### ISSUE TITLE
Share links should open Android app immediately when possible

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#280] opened 2015-07-14 20:15 UTC
This issue has been migrated from mozilla/webmaker-android#2396.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Thu Jul 09 2015 and had the following description:

> beta.webmaker.org links open projects in mobile browser. User has to click on thumbnail in browser to open in app. Should skip that step and go right into app.

On Thu Jul 09 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****secretrobotron** This seems pretty straight foward to implement on the android side of things, do you mind adding the android label to this? 

On Thu Jul 09 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> **@****ryanw-se** this is a regression, right? Any reason it changed?

On Thu Jul 09 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****secretrobotron** Possibly, I'd have to look into it further to confirm. Its most likely due to a change in the URL or something of that sort, the Android code base is relatively stable.

On Tue Jul 14 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> **@****ryanw-se** were you able to make any progress on this?

On Tue Jul 14 2015, [ryanw-se](https://api.github.com/users/ryanw-se) commented:

> **@****secretrobotron** Its most likely a issue of some sort regarding mozilla/webmaker-browser/136. I'm not really familiar with that code base so if **@****k88hudson** could check that PR out and make sure no issues are originating from there, I'd appreciate it!

On Tue Jul 14 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> :+1: thanks **@****ryanw-se** 

On Tue Jul 14 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> **@****k88hudson** looks like https://github.com/mozilla/webmaker-browser/pull/136 may have broken the experience for native app users. I'm no longer dropped straight into the app, but pushed to browser first (on Android).

**Comment by k88hudson** [comment] 2015-07-16 15:30
This is not a regression, it's an unfortunate consequence of recent changes to the Android/Chrome security policy regarding opening app intents from a browser (they must be initiated from a user gesture like a tap)

Docs: https://developer.chrome.com/multidevice/android/intents

**Comment by secretrobotron** [comment] 2015-07-16 15:31
Wow! That's too bad. I hadn't noticed this from other apps on my phone yet, but maybe I just haven't used other apps this way in a while. Any other examples?

**Comment by k88hudson** [comment] 2015-07-16 15:32
What kind of examples are you looking for?

Also, aren't we getting rid of this view when the player is ready?

**Comment by secretrobotron** [comment] 2015-07-16 15:42
Yeah, but I was hoping we would skip the web view altogether for people who have the app installed.

Any examples of other apps that do things like this? Lucy and I are experimenting.

**Comment by k88hudson** [comment] 2015-07-16 15:46
> The functionality has changed slightly in Chrome for Android, versions 25 and later. It is no longer possible to launch an Android app by setting an iframe's src attribute. For example, navigating an iframe to a URI with a custom scheme such as paulsawesomeapp:// will not work even if the user has the appropriate app installed. Instead, you should implement a user gesture to launch the app via a custom scheme, or use the “intent:” syntax described in this article.

**Comment by secretrobotron** [comment] 2015-07-16 15:49
And `intent:` doesn't help (without really knowing what that does..)?

**Comment by k88hudson** [comment] 2015-07-16 15:54
Unfortunately not :( That's a url scheme you can use in an `href` attribute on an anchor tag, as opposed to hooking into a `touchstart` event or something. I'm pretty sure the change happened because advertisers were abusing the launch on page load, kind of like super annoying pop-ups. 

If you _do_ find an example of it working somewhere though, let me know... I spend quite a bit of time trying to find an alternate solution, but it's definitely possible I missed something

**Comment by k88hudson** [comment] 2015-07-16 15:56
That said I think it would be worth syncing up with gavin here https://github.com/mozilla/webmaker-core/issues/295 to make sure the flow makes sense in terms of when to launch the app, when to launch the browser player, when to show the download CTA etc. The design here doesn't seem to cover the mobile case https://cloud.githubusercontent.com/assets/53411/8630069/855c9e9c-272f-11e5-8d75-18e5c85091a2.png

**Comment by k88hudson** [comment] 2015-07-20 20:40
@secretrobotron is the scope of this work covered in other tickets? can i close this one?

**Comment by secretrobotron** [comment] 2015-07-20 21:08
@k88hudson yep!

**Closed as completed by secretrobotron** 2015-07-20 21:08 UTC
Labels: bug, android, assigned-to-contributor
