### ISSUE TITLE
QA/Testing scripts

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-core#279] opened 2015-07-14 20:15 UTC
This issue has been migrated from mozilla/webmaker-android#2395.

It was originally written by [secretrobotron](https://api.github.com/users/secretrobotron) on Wed Jul 08 2015 and had the following description:

> Prior work by **@****k88hudson** here: https://gist.github.com/k88hudson/16e0b6a720f33e1f7c3e
> Some more brainstorming here: https://etherpad.mozilla.org/webmaker-qa-stuff-vectors
> - How do we split this up into small, repeatable tasks that people can jump in and test?
> - Does it cover localization, QA, and user-testing?
> 
> cc **@****flukeout** 

On Wed Jul 08 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> QA Checklist for Localization: https://github.com/mozilla/webmaker-android/issues/2061

On Wed Jul 08 2015, [secretrobotron](https://api.github.com/users/secretrobotron) commented:

> Would rather use https://github.com/mozilla/webmaker-core/issues/16, but there are no labels/milestones. Help, **@****xmatthewx** ?

**Comment by xmatthewx** [comment] 2015-07-16 18:11
duplicate of #16

**Closed as completed by xmatthewx** 2015-07-16 18:11 UTC
