### ISSUE TITLE
Project Settings page throws script errors

### ISSUE THREAD

**Issue by cadecairos** [mozilla/webmaker-core#542] opened 2015-08-14 17:43 UTC
```
Uncaught ReferenceError: Could not find Intl message: badTitle
ReactCompositeComponent.js?cd59*****:723 Uncaught TypeError: Cannot read property '_currentElement' of null
```

STR: 
1. Open a project from the Make tab
2. press the three dots button, select settings

Expected: Settings tab should load
Actual: blank page, frozen app. Must force close to fix it. console errors above.

**Comment by xmatthewx** [comment] 2015-08-14 17:53
Is this just on develop/staging? Related to style guide button? If not, sounds critical. @k88hudson @thisandagain

**Comment by cadecairos** [comment] 2015-08-14 17:55
I just downloaded the nightly  from mzl.la/webmaker-nightly

**Comment by thisandagain** [comment] 2015-08-14 17:57
Confirmed in RC. Needs to be resolved prior to ship. @k88hudson can you take this?

**Comment by k88hudson** [comment] 2015-08-14 18:21
When testing current master, I can't reproduce this; I am pretty sure this is a result of a proper rebuild not being run (so new locale files weren't generated) since `badTitle` was added very recently. Thoughts @thisandagain?

**Comment by thisandagain** [comment] 2015-08-14 18:31
I just did another fresh install / build. Perhaps some kind of merge issue? Hmm.

**Comment by thisandagain** [comment] 2015-08-14 19:24
Confirmed as a build issue. Closing.

**Closed as completed by thisandagain** 2015-08-14 19:24 UTC
Labels: bug, critical
