### ISSUE TITLE
Offline - Error messages when attempting to sign-up / log-in are confusing

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-core#433] opened 2015-07-28 23:29 UTC
The error messages that a user receives when attempting to log-in or create an account while offline are quite confusing:

**Log-In**
"Error trying to log in"
"Looks like there might be a problem with your username or password"

**Sign-Up**
"Error while trying to sign up"
"Something went wrong"

@vazquez could you spec out some copy for this edge case?

**Comment by vazquez** [comment] 2015-07-29 17:09
Sign-In
"We need an Internet connection to sign you in."

Sign-Up
"You’re offline. Enable Wi-Fi to talk to the Internet."

What do you think @thisandagain?

**Comment by thisandagain** [comment] 2015-07-29 20:49
@vazquez Perhaps, "Please connect to the internet to sign in" is more direct / clear? On the second one (sign-up) it's problematic to call out Wifi as most users are on a cell network.

**Comment by vazquez** [comment] 2015-07-29 21:07
@thisandagain  - Hah! My bad on the Wi-Fi, brain went to sleep.

Sign-In
"Please connect to the Internet to sign in."

Sign-Up
"We need an Internet connection to create an account."

**Comment by thisandagain** [comment] 2015-07-29 21:16
Great! Thanks. :+1:

**Comment by k88hudson** [comment] 2015-08-04 16:24
@vazquez just for some clarification, do you want me to:

a) detect offline status separately, have different error messages for being offline v.s. not being able to connect to the server (which could be caused by the server being down etc.)
b) use the same error message for all connection problems

I'm assuming`Please connect to the Internet to sign in` is somewhat misleading if the error case is that the server is offline, let me know what you think.

See the comments around https://github.com/mozilla/webmaker-core/compare/develop...k88hudson:gh433?expand=1#diff-0dd2d124e519d95b48de1bc23e249fa1R155 for all possible error cases

**Comment by k88hudson** [comment] 2015-08-04 16:28
cc @thisandagain, can you maybe help clarify?

**Comment by thisandagain** [comment] 2015-08-04 18:15
@k88hudson Good question. I filed this specifically for "A" in which the error message should be different when the user does not have an internet connection.

**Comment by thisandagain** [comment] 2015-08-04 18:27
Sketch of method for returning network status using `ping` of API:

``` java
public Boolean isAvailable() {
    try { 
        Process p1 = java.lang.Runtime.getRuntime().exec("ping -c 1    api.webmaker.org");
        int returnVal = p1.waitFor();
        boolean reachable = (returnVal==0);
        if(reachable){
            System.out.println("Internet access");
            return reachable;
        } 
        else{ 
            System.out.println("No Internet access");
        } 

    } catch (Exception e) {
        e.printStackTrace();
    } 

    return false; 
} 
```

**Comment by k88hudson** [comment] 2015-08-05 18:57
Resolved by https://github.com/k88hudson/webmaker-core/commit/555a1a508412e55fded88f438178ad6652d86ed7 and https://github.com/k88hudson/webmaker-core/commit/9fd1d7388a514ade1a7fa02674f162f3b584b982

**Closed as completed by k88hudson** 2015-08-05 18:57 UTC
Labels: bug, critical
