### ISSUE TITLE
Text postion can't be set at the top/bottom of page

### ISSUE THREAD

**Issue by ioana-chiorean** [mozilla/webmaker-core#817] opened 2015-11-18 22:29 UTC
1. I am trying to move the text above the picture. 
2. I am able only till a point. 
3. I can move the picture thought 
4. Try to set the text at the bottom of the page

max position:
<img src="https://cloud.githubusercontent.com/assets/1391451/11256376/40c3bca2-8e54-11e5-866d-ea96f6cb5343.jpg" width="300" height="550" /> 
<img src="https://cloud.githubusercontent.com/assets/1391451/11256377/40f5ff96-8e54-11e5-80ad-12c8771e1bc0.jpg" width="300" height="550" /> 

image can be moved:
<img src="https://cloud.githubusercontent.com/assets/1391451/11256378/40fbe1b8-8e54-11e5-8149-14da01a07974.jpg" width="300" height="550" />

**Comment by alanmoo** [comment] 2015-11-19 17:08
Duplicate of #710, which should be addressed by #735

**Comment by ioana-chiorean** [comment] 2015-11-19 21:31
well I think it is worse than "small text elements"

**Comment by alanmoo** [comment] 2015-11-19 21:32
It is, though I believe I've solved for all cases with that code.

**Comment by ioana-chiorean** [comment] 2015-11-20 09:50
I am able to set them now anywhere on the page with 1.5.1:

<img src="https://cloud.githubusercontent.com/assets/1391451/11296720/86d6a406-8f7c-11e5-9b94-5011f1d523cf.jpg" width="300" height="550" />

**Closed as completed** 2015-11-20 13:37 UTC
Labels: bug
